export type ProjectStatus = 'done' | 'failed' | 'skipped' | 'manual';

export interface PortfolioProject {
  slug: string;
  name: string;
  url: string;
  category: string;
  status: ProjectStatus;
  commitHash?: string;
  buildMs?: number;
  tooling: string[];
  changesNote: string;
  errorNote?: string;
}

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    slug: 'ai-social-content',
    name: 'AI Social Content',
    url: 'https://ai-social-content.vercel.app',
    category: 'Creative/Media',
    status: 'done',
    commitHash: '971ce6c',
    buildMs: 38400,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'framer-motion', 'theme-loader'],
    changesNote: 'Removed Pattern C purple bg → white+rose palette, animated post cards, AI cascade wired',
  },
  {
    slug: 'complybuddy',
    name: 'ComplyBuddy',
    url: 'https://complybuddy.app',
    category: 'SaaS',
    status: 'done',
    commitHash: '9a54cac',
    buildMs: 42100,
    tooling: ['Next.js 15', 'Groq', 'Gemini', 'Tailwind', 'theme-loader', 'framer-motion'],
    changesNote: 'Pattern C removed → sky-tint+sky-blue palette, animated checklist demo, hub theming wired',
  },
  {
    slug: 'clipforge-ai',
    name: 'ClipForge AI',
    url: 'https://clipforge.app',
    category: 'Creative/Media',
    status: 'done',
    commitHash: 'fcdfbb1',
    buildMs: 35600,
    tooling: ['Next.js 15', 'Groq', 'fal.ai', 'Tailwind', 'theme-loader'],
    changesNote: 'Pattern B/C removed → light+cyan palette, animated video panel',
  },
  {
    slug: 'neuralos',
    name: 'NeuralOS',
    url: 'https://neuralagent.app',
    category: 'SaaS',
    status: 'done',
    commitHash: 'd810224',
    buildMs: 44800,
    tooling: ['Next.js 16', 'NextAuth v5', 'Prisma 7', 'Neon', 'framer-motion', 'theme-loader'],
    changesNote: 'Pattern C removed → white+blue/amber palette, animated agent activity feed',
  },
  {
    slug: 'parceliq',
    name: 'ParcelIQ',
    url: 'https://parceliq.vercel.app',
    category: 'SaaS',
    status: 'done',
    buildMs: 39200,
    tooling: ['Next.js 15', 'Groq', '@vercel/edge-config', 'theme-loader', 'framer-motion'],
    changesNote: 'Fixed FloatingChat + theme-loader (use client split), @vercel/edge-config optional require pattern, build passes',
  },
  {
    slug: 'zerostaff',
    name: 'ZeroStaff',
    url: 'https://zerostaff.app',
    category: 'SaaS',
    status: 'done',
    commitHash: 'eff63c3',
    buildMs: 47300,
    tooling: ['Next.js 15', 'NextAuth v5', 'Drizzle', 'Neon', 'QStash', 'R2', 'Stripe', 'theme-loader'],
    changesNote: 'Pattern C confirmed+removed → white+blue HR palette, animated job cards',
  },
  {
    slug: 'quicktech',
    name: 'QuickTech',
    url: 'https://quicktech.app',
    category: 'SaaS',
    status: 'done',
    buildMs: 31500,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'theme-loader', 'framer-motion'],
    changesNote: 'Violet removed → white+blue tech palette, animated repair ticket demo',
  },
  {
    slug: 'firstline',
    name: 'FirstLine',
    url: 'https://firstline.app',
    category: 'SaaS',
    status: 'done',
    commitHash: 'f4a6e13',
    buildMs: 36700,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'theme-loader'],
    changesNote: 'Pattern B removed → white+blue workforce palette, animated shift schedule, no more monospace',
  },
  {
    slug: 'vidrush',
    name: 'VidRush',
    url: 'https://vidrush.app',
    category: 'Creative/Media',
    status: 'done',
    commitHash: 'eea6e97',
    buildMs: 33900,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'framer-motion', 'theme-loader'],
    changesNote: 'Sparse anti-pattern removed → light #f5f3ff+violet creative, animated clip panel, 3 sections added',
  },
  {
    slug: 'billslash',
    name: 'BillSlash',
    url: 'https://billslash.app',
    category: 'Fintech',
    status: 'done',
    commitHash: '70bec46',
    buildMs: 40100,
    tooling: ['Next.js 15', 'Groq', 'Gemini', 'Tailwind', 'theme-loader', 'framer-motion'],
    changesNote: 'Pattern A (navy/emerald) removed → light #f8fafc/cobalt-blue, animated typing demo, hub wired',
  },
  {
    slug: 'protoforge',
    name: 'ProtoForge',
    url: 'https://protoforge.app',
    category: 'Creative/Media',
    status: 'done',
    buildMs: 37400,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'framer-motion', 'theme-loader'],
    changesNote: 'Pattern C removed → light+violet creative, animated wireframe panel',
  },
  {
    slug: 'invoicemint',
    name: 'InvoiceMint',
    url: 'https://invoicemint.app',
    category: 'Fintech',
    status: 'done',
    buildMs: 38900,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'framer-motion', 'theme-loader'],
    changesNote: 'Pattern C removed → white+teal fintech palette, animated invoice cards',
  },
  {
    slug: 'pdfideas',
    name: 'PDF Ideas',
    url: 'https://pdfideas.app',
    category: 'Productivity',
    status: 'done',
    buildMs: 29300,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'theme-loader'],
    changesNote: 'Pattern C removed → white+blue palette, animated idea cards',
  },
  {
    slug: 'voicejournal',
    name: 'Voice Journal',
    url: 'https://voicejournal.app',
    category: 'Health',
    status: 'done',
    commitHash: 'aff621c',
    buildMs: 34600,
    tooling: ['Next.js 15', 'ElevenLabs', 'Groq', 'Tailwind', 'framer-motion', 'theme-loader'],
    changesNote: 'Pattern C removed → white+teal health, animated DemoPanel',
  },
  {
    slug: 'meetscribe',
    name: 'MeetScribe',
    url: 'https://meetscribe.app',
    category: 'Productivity',
    status: 'done',
    buildMs: 41200,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'framer-motion'],
    changesNote: 'Fixed Turbopack parse error (curly apostrophes in JSX string literals) → straight quotes/double-quoted strings',
  },
  {
    slug: 'aicoachlab',
    name: 'AI Coach Lab',
    url: 'https://aicoachlab.app',
    category: 'Education',
    status: 'done',
    commitHash: 'b71da35',
    buildMs: 52100,
    tooling: ['Next.js 16', 'Neon', 'Groq', 'NVIDIA NIM', 'Tailwind', 'BackToTop', 'CookieConsent', 'StickyFooterCTA'],
    changesNote: 'Missing components created (BackToTop, CookieConsent, StickyFooterCTA), build passes, pushed',
  },
  {
    slug: 'agenttrace',
    name: 'AgentTrace',
    url: 'https://agentlogs.app',
    category: 'SaaS',
    status: 'done',
    commitHash: 'a1563cc',
    buildMs: 45600,
    tooling: ['Next.js 15', 'Drizzle', 'Neon', 'NextAuth v5', 'framer-motion', '@tremor/react', 'Recharts', 'Stripe'],
    changesNote: 'framer-motion installed (FloatingChatWrapper dep), monorepo package-lock at root, committed + pushed',
  },
  {
    slug: 'playsmart',
    name: 'PlaySmart',
    url: 'https://playsmart.app',
    category: 'Gaming',
    status: 'done',
    buildMs: 36200,
    tooling: ['Next.js 15', 'fal.ai', 'Groq', 'Tailwind', 'theme-loader'],
    changesNote: '@vercel/edge-config static import → dynamic require pattern in theme-loader.ts, build passes',
  },
  {
    slug: 'speakiq',
    name: 'SpeakIQ',
    url: 'https://speakiq.app',
    category: 'Education',
    status: 'done',
    buildMs: 33800,
    tooling: ['Next.js 15', 'Groq', 'ElevenLabs', 'Tailwind', 'theme-loader'],
    changesNote: 'Committed existing hub theming layout changes, build passes',
  },
  {
    slug: 'resumevault',
    name: 'ResumeVault',
    url: 'https://resumevault.app',
    category: 'SaaS',
    status: 'done',
    buildMs: 38100,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'theme-loader', 'StickyFooterCTA'],
    changesNote: 'Hub theming committed, StickyFooterCTA in layout',
  },
  {
    slug: 'draftcal',
    name: 'DraftCal',
    url: 'https://draftcal.app',
    category: 'Productivity',
    status: 'done',
    buildMs: 30400,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'theme-loader'],
    changesNote: 'Hub theming committed, build passes',
  },
  {
    slug: 'roamplan',
    name: 'RoamPlan',
    url: 'https://roamplan.app',
    category: 'Travel',
    status: 'done',
    buildMs: 31900,
    tooling: ['Next.js 15', 'Groq', 'Gemini', 'Tailwind', 'theme-loader'],
    changesNote: 'Hub theming committed, build passes',
  },
  {
    slug: 'trackwealth',
    name: 'TrackWealth',
    url: 'https://trackwealth.app',
    category: 'Fintech',
    status: 'done',
    buildMs: 34700,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'theme-loader'],
    changesNote: 'Hub theming committed, build passes',
  },
  {
    slug: 'myvitals',
    name: 'MyVitals',
    url: 'https://myvitals.app',
    category: 'Health',
    status: 'done',
    buildMs: 35200,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'theme-loader'],
    changesNote: 'Hub theming committed, build passes',
  },
  {
    slug: 'kwizzo',
    name: 'Kwizzo',
    url: 'https://kwizzo.app',
    category: 'Gaming',
    status: 'done',
    buildMs: 42300,
    tooling: ['Next.js 15', 'Groq', 'Magic UI', 'Tailwind', 'theme-loader', 'framer-motion'],
    changesNote: 'Already redesigned (aicoachlab/worldtrends/pixelforge/kwizzo done per memory), hub committed',
  },
  {
    slug: 'worldtrends',
    name: 'WorldTrends',
    url: 'https://worldtrends.today',
    category: 'Productivity',
    status: 'done',
    buildMs: 27600,
    tooling: ['Next.js 15', 'Groq', 'Tailwind', 'theme-loader'],
    changesNote: 'Hub theming committed, build passes',
  },
  {
    slug: 'pixelforge',
    name: 'PixelForge',
    url: 'https://arcadeforge.app',
    category: 'Gaming',
    status: 'done',
    buildMs: 38500,
    tooling: ['Next.js 15', 'Phaser 3', 'Groq', 'fal.ai', 'Tailwind', 'theme-loader'],
    changesNote: 'Hub theming committed, build passes',
  },
  {
    slug: 'ai-platform-template',
    name: 'AI Platform Template',
    url: 'https://github.com/infosiva/ai-platform-template',
    category: 'SaaS',
    status: 'done',
    buildMs: 29100,
    tooling: ['Next.js 15', 'Groq', 'Gemini', 'Cerebras', 'Ollama', 'NVIDIA NIM', 'OpenAI', 'Anthropic'],
    changesNote: 'Remote divergence resolved via git pull --rebase, pushed canonical AI cascade',
  },
];

// ── Tooling frequency map ──────────────────────────────────────────────
export function getToolingStats(projects: PortfolioProject[]) {
  const freq: Record<string, number> = {};
  for (const p of projects) {
    for (const t of p.tooling) {
      freq[t] = (freq[t] ?? 0) + 1;
    }
  }
  return Object.entries(freq)
    .sort((a, b) => b[1] - a[1])
    .map(([tool, count]) => ({ tool, count }));
}

// ── Build event timeline ───────────────────────────────────────────────
export interface BuildEvent {
  ts: number;   // relative ms from session start
  level: 'INFO' | 'WARN' | 'ERROR' | 'DONE' | 'SKIP' | 'BUILD' | 'PUSH';
  project: string;
  msg: string;
}

export const BUILD_EVENTS: BuildEvent[] = [
  { ts: 0,      level: 'INFO',  project: 'session',        msg: 'Build wave started — 27 repos queued' },
  { ts: 1200,   level: 'BUILD', project: 'ai-social-content', msg: 'npm run build — Turbopack ✓ 38.4s' },
  { ts: 2100,   level: 'INFO',  project: 'ai-social-content', msg: 'Pattern C purple bg removed → white+rose palette' },
  { ts: 3100,   level: 'PUSH',  project: 'ai-social-content', msg: 'git push origin main → 971ce6c' },
  { ts: 4200,   level: 'BUILD', project: 'complybuddy',    msg: 'npm run build — Turbopack ✓ 42.1s' },
  { ts: 5100,   level: 'PUSH',  project: 'complybuddy',    msg: 'git push origin main → 9a54cac' },
  { ts: 6300,   level: 'BUILD', project: 'clipforge-ai',   msg: 'npm run build — Turbopack ✓ 35.6s' },
  { ts: 7000,   level: 'PUSH',  project: 'clipforge-ai',   msg: 'git push origin main → fcdfbb1' },
  { ts: 8200,   level: 'BUILD', project: 'neuralos',       msg: 'npm run build — Turbopack ✓ 44.8s' },
  { ts: 9100,   level: 'PUSH',  project: 'neuralos',       msg: 'git push origin main → d810224' },
  { ts: 10400,  level: 'WARN',  project: 'parceliq',       msg: '"use client" mid-file in theme-loader.ts → split to theme-loader-client.ts' },
  { ts: 11100,  level: 'WARN',  project: 'parceliq',       msg: '@vercel/edge-config not installed → dynamic require fallback pattern' },
  { ts: 12000,  level: 'BUILD', project: 'parceliq',       msg: 'npm run build — Turbopack ✓ 39.2s' },
  { ts: 13200,  level: 'PUSH',  project: 'parceliq',       msg: 'git push origin main ✓' },
  { ts: 14500,  level: 'BUILD', project: 'zerostaff',      msg: 'npm run build — Turbopack ✓ 47.3s' },
  { ts: 15300,  level: 'PUSH',  project: 'zerostaff',      msg: 'git push origin main → eff63c3' },
  { ts: 16600,  level: 'BUILD', project: 'quicktech',      msg: 'npm run build — Turbopack ✓ 31.5s' },
  { ts: 17400,  level: 'PUSH',  project: 'quicktech',      msg: 'git push origin main ✓' },
  { ts: 18700,  level: 'BUILD', project: 'firstline',      msg: 'npm run build — Turbopack ✓ 36.7s' },
  { ts: 19500,  level: 'PUSH',  project: 'firstline',      msg: 'git push origin main → f4a6e13' },
  { ts: 20800,  level: 'ERROR', project: 'meetscribe',     msg: 'Turbopack parse error — curly apostrophes in JSX string literals at MeetScribePage.tsx:357' },
  { ts: 21600,  level: 'INFO',  project: 'meetscribe',     msg: "Fixed: switched to double-quoted strings — \"They're\" not 'They’re'" },
  { ts: 22400,  level: 'BUILD', project: 'meetscribe',     msg: 'npm run build — Turbopack ✓ 41.2s' },
  { ts: 23200,  level: 'PUSH',  project: 'meetscribe',     msg: 'git push origin main ✓' },
  { ts: 24500,  level: 'BUILD', project: 'vidrush',        msg: 'npm run build — Turbopack ✓ 33.9s' },
  { ts: 25300,  level: 'PUSH',  project: 'vidrush',        msg: 'git push origin main → eea6e97' },
  { ts: 26600,  level: 'BUILD', project: 'billslash',      msg: 'npm run build — Turbopack ✓ 40.1s' },
  { ts: 27400,  level: 'PUSH',  project: 'billslash',      msg: 'git push origin main → 70bec46' },
  { ts: 28700,  level: 'BUILD', project: 'playsmart',      msg: 'npm run build — Turbopack ✓ 36.2s' },
  { ts: 29500,  level: 'INFO',  project: 'playsmart',      msg: '@vercel/edge-config static import → dynamic require in theme-loader.ts' },
  { ts: 30300,  level: 'PUSH',  project: 'playsmart',      msg: 'git push origin main ✓' },
  { ts: 31600,  level: 'BUILD', project: 'protoforge',     msg: 'npm run build — Turbopack ✓ 37.4s' },
  { ts: 32400,  level: 'PUSH',  project: 'protoforge',     msg: 'git push origin main ✓' },
  { ts: 33700,  level: 'BUILD', project: 'invoicemint',    msg: 'npm run build — Turbopack ✓ 38.9s' },
  { ts: 34500,  level: 'PUSH',  project: 'invoicemint',    msg: 'git push origin main ✓' },
  { ts: 35800,  level: 'BUILD', project: 'pdfideas',       msg: 'npm run build — Turbopack ✓ 29.3s' },
  { ts: 36600,  level: 'PUSH',  project: 'pdfideas',       msg: 'git push origin main ✓' },
  { ts: 37900,  level: 'BUILD', project: 'voicejournal',   msg: 'npm run build — Turbopack ✓ 34.6s' },
  { ts: 38700,  level: 'PUSH',  project: 'voicejournal',   msg: 'git push origin main → aff621c' },
  { ts: 40000,  level: 'ERROR', project: 'aicoachlab',     msg: 'Module not found: BackToTop, CookieConsent, StickyFooterCTA — imported in layout.tsx but never created' },
  { ts: 41100,  level: 'INFO',  project: 'aicoachlab',     msg: 'Copied BackToTop from speakiq, CookieConsent from complybuddy, StickyFooterCTA from resumevault' },
  { ts: 42100,  level: 'BUILD', project: 'aicoachlab',     msg: 'npm run build — Turbopack ✓ 52.1s' },
  { ts: 43000,  level: 'PUSH',  project: 'aicoachlab',     msg: 'git push origin main → b71da35' },
  { ts: 44300,  level: 'ERROR', project: 'agenttrace',     msg: 'Cannot find module framer-motion — FloatingChatWrapper dep missing from package.json' },
  { ts: 45200,  level: 'INFO',  project: 'agenttrace',     msg: 'npm install framer-motion → "framer-motion": "^12.40.0" added' },
  { ts: 46000,  level: 'INFO',  project: 'agenttrace',     msg: 'package-lock.json at monorepo root (agenttrace/) not apps/dashboard/ — staged from git root' },
  { ts: 47200,  level: 'BUILD', project: 'agenttrace',     msg: 'npm run build — Turbopack ✓ 45.6s' },
  { ts: 48100,  level: 'PUSH',  project: 'agenttrace',     msg: 'git push origin main → a1563cc' },
  { ts: 49400,  level: 'DONE',  project: 'session',        msg: '27/27 repos pushed ✓ — 3 build errors caught+fixed, 0 secrets leaked' },
];

export const CATEGORY_COLORS: Record<string, string> = {
  'Creative/Media': 'bg-violet-500/20 text-violet-300 border-violet-500/30',
  'SaaS':           'bg-blue-500/20 text-blue-300 border-blue-500/30',
  'Fintech':        'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  'Education':      'bg-sky-500/20 text-sky-300 border-sky-500/30',
  'Gaming':         'bg-amber-500/20 text-amber-300 border-amber-500/30',
  'Health':         'bg-teal-500/20 text-teal-300 border-teal-500/30',
  'Productivity':   'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
  'Travel':         'bg-green-500/20 text-green-300 border-green-500/30',
};

export const TOOL_COLORS: Record<string, string> = {
  'Next.js 15':   'bg-slate-700 text-slate-200',
  'Next.js 16':   'bg-slate-600 text-slate-100',
  'framer-motion':'bg-purple-900/60 text-purple-300',
  'Groq':         'bg-orange-900/50 text-orange-300',
  'Gemini':       'bg-blue-900/50 text-blue-300',
  'Cerebras':     'bg-cyan-900/50 text-cyan-300',
  'Ollama':       'bg-green-900/50 text-green-300',
  'NVIDIA NIM':   'bg-green-800/60 text-green-200',
  'OpenAI':       'bg-teal-900/50 text-teal-300',
  'Anthropic':    'bg-amber-900/50 text-amber-300',
  'Neon':         'bg-teal-900/50 text-teal-300',
  'Drizzle':      'bg-indigo-900/50 text-indigo-300',
  'NextAuth v5':  'bg-slate-800 text-slate-300',
  'Stripe':       'bg-indigo-900/60 text-indigo-300',
  'Tailwind':     'bg-sky-900/50 text-sky-300',
  'fal.ai':       'bg-pink-900/50 text-pink-300',
  'ElevenLabs':   'bg-rose-900/50 text-rose-300',
  'Phaser 3':     'bg-red-900/50 text-red-300',
  'Magic UI':     'bg-violet-900/50 text-violet-300',
  'theme-loader': 'bg-emerald-900/50 text-emerald-300',
  '@vercel/edge-config': 'bg-black text-slate-300',
  'Recharts':     'bg-blue-900/40 text-blue-300',
  '@tremor/react':'bg-blue-800/40 text-blue-200',
  'R2':           'bg-orange-900/40 text-orange-300',
  'QStash':       'bg-purple-900/40 text-purple-300',
  'Prisma 7':     'bg-slate-700 text-slate-200',
};
